### PR TITLE
The current version will not work with Rails 4.

### PR DESCRIPTION
**Pull request by hazah**
This is an update to use the v1.3.0 of spine, so that the coffescripts compile properly and produce the expected JS.

### CODE REVIEW

**Comment by ch1ago** [comment]
I am currently evaluating front-end frameworks for our company.
Without this patch spine-rails won't load in Rails4. Thanks @hazah :heart: 

@maccman please check this patch for merging :+1:

**Comment by hazah** [comment]
@yakko My pleasure.

**Comment by ch1ago** [comment]
@aeischeid @cengebretson @adambiggs some love in here guys :heart:

**Comment by jona** [comment]
I'm in need of rails 4 support as well. This would be great! @hazah how heavily have you tested your changes?

**Comment by hazah** [comment]
The main change is that it goes from not working at all to working as advertized. However I've not inspected every nook and cranny. I'm fairly certain it's as tested as the actual spine framework of this version since this gem does nothing except incorporate those files into the pipeline.

**Comment by aeischeid** [comment]
normally @zohararad or @b3njamin are the maintainers here. I do not use spine-rails at all, but I can merge this if needed. It seems fairly safe.

**Comment by zohararad** [comment]
I'm happy to merge but since I have no way of publishing the Gem (not does @b3njamin afaik) maintaing this repo is a bit of a no-go and I'm sorry to say I haven't actively touched it for a very long while

**Comment by aeischeid** [comment]
@maccman are you able to publish gems? We've had some requests for an update to the spine rails gem

**Comment by ch1ago** [comment]
@gertig please take a look at it ASAP

**Comment by hazah** [comment]
Whomever is involved, please understand that this gem is completely useless with the current coffeescript environment, so an official release is absolutely necessary for any forward motion.

**Comment by hazah** [comment]
Just curious to know, when will this gem be updated on rubygems.org? Cheers.

**Comment by aeischeid** [comment]
I have zero experience with publishing gems. @maccman was the originator so he may have some idea how to do this or know someone who does and cares to take the time, other than that you might want to find other people who would have the skills and time. I would be happy to add someone as a maintainer of this if they wanted to fill that role.

**Comment by hazah** [comment]
@aeischeid If the only problem with publishing the gem is account access, then I wouldn't mind pushing that though for you, provided you can give me the access I'd need. Gotta learn at some point :)

**Comment by aeischeid** [comment]
@hazah I can add you as a contributor for this project if that is what you mean

**Comment by hazah** [comment]
@aeischeid For rubygems? Because that's all I'm aiming to do. Push this new version to be available for all. If that's what you mean then I'm game.

**Comment by aeischeid** [comment]
@hazah it's done, push some gems!

**Pull request merged**
