### PR TITLE
Update Spine source to 1.2.0 to fix sorting in Chrome

### PR DESCRIPTION
**Pull request by Jurawa**
Spine 1.1.0 has an issue with not respecting sort order of records returned from the DB in Chrome. This was fixed in Spine 1.2.0 - see spine/spine#483.

I updated the spine source to 1.2.0 and tested the ordering issue... All fixed. Submitting a pull request.

### CODE REVIEW

**Comment by gvt** [comment]
Can we get a release of the spine-rails gem that incorporates this pull request? The bug that breaks sorting in Chrome is a real pain.

**Comment by whatyoubendoing** [comment]
Hi @gvt, Sorry, we dont have the rights to publish the gem. That falls down to @maccman.

**Comment by Jurawa** [comment]
Thanks for merging @benjaminhainez. @maccman When you get a chance it would be awesome to get a release of the gem. Cheers

**Comment by maccman** [comment]
Done! Sorry for the delay guys.

**Comment by Jurawa** [comment]
Sweet thanks!

**Pull request merged**
