### PR TITLE
Update to v1.10

### PR DESCRIPTION
**Pull request by whatyoubendoing**
- Change .gitkeep to .keep files
- Update hashes to ruby 1.9 style
- Add build script
- Change from javascript source to coffeescript source to add support for source maps

### CODE REVIEW

**Comment by zohararad** [comment]
@benhainez how shall we proceed with this. How would you like to divide work on the Gem?

**Comment by whatyoubendoing** [comment]
@zohararad ah not sure, have you had a check over the code in this pull reques? If you are happy for me to merge this back in we can go from here. 

@maccman how would you like to go about managing the deployment of this gem?

**Comment by zohararad** [comment]
@benhainez I went over the commits, and they seem fine to me and very much inline with keeping this gem up to date.

My only very slight concern is adding some sort of tests to make sure everything is there.

I can try and add these after you merge and before you release by week's end, unless you have time to do it before but i dont think it's a show stopper.

**Comment by whatyoubendoing** [comment]
Yes there is one bug with Spine 1.1.0 which will be included in this pull request. However I am going to merge the request tag it and import the latest from master. One other thing we need to update is the generators as jQuery.sub() is depreciated in jQuery version 1.9

**Pull request merged**
